
services:
  goocr:
    image: chiora93/goocr
    privileged: true
    environment:
      - UPLOADED_FILES_DIR=/tmp/pdf-cache
    build:
      context: .
      args:
        - TARGETOS=linux
        - TARGETARCH=amd64
    ports:
      - 8777:80
    volumes:
      - /tmp/pdf-cache:/tmp/pdf-cache